policy_wizard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.process_lti_launch_request_view, name='process_lti_launch_request'),
    path('refresh', views.lti_exception_view, name='lti_exception_view'),
    path('policy_templates_list/', views.policy_templates_list_view, name='policy_templates_list'),
    path('student_active_policy/', views.student_active_policy_view, name='student_active_policy'),
    path('template/<int:pk>/edit/', views.admin_level_template_edit_view, name='admin_level_template_edit'),
    path('updated_template/<int:pk>/', views.admin_updated_template_view, name='admin_updated_template'),
    path('edit_updated_template/<int:pk>/edit/', views.admin_edit_updated_template_view, name='admin_edit_updated_template'),
    path('policy/<int:pk>/edit/', views.instructor_level_policy_edit_view, name='instructor_level_policy_edit'),
    path('active_policy/<int:pk>/', views.instructor_active_policy, name='instructor_active_policy'),
    path('edit_active_policy/<int:pk>/', views.edit_active_policy, name='edit_active_policy'),
    path('instructor_inactivate_policies/', views.instructor_inactivate_policies_view, name='instructor_inactivate_policies'),
]

policy_wizard/models.py
from django.db import models
from tinymce import models as tinymce_models

# Create your models here.

#Policy Templates
class PolicyTemplates(models.Model):
    name = models.CharField(max_length=255)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

#Published policies
class Policies(models.Model):
    course_id = models.IntegerField(null=True)
    context_id = models.CharField(max_length=255, null=True)
    related_template = models.ForeignKey(PolicyTemplates, null=True, on_delete=models.CASCADE, related_name="related_policies")
    is_published = models.SmallIntegerField()
    published_by = models.CharField(max_length=255)
    is_active = models.SmallIntegerField()
    body = tinymce_models.HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

templates/admin_edit_updated_template.html
{% extends 'tinymce_editor_base.html' %}

{% comment %}
    Presents the text editor to an administrator so they can re-edit a template they
    just updated
{% endcomment %}

{% block editorContent %}

        <div class="row">
            <div class="col-sm-12" style="padding-right: 20px; padding-left: 40px">

                <div class="row">
                    <div class="col-xs-12 page-header">
                        <h1>AI Policy Wizard</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert custom-alert-info">
                            <p><strong>Edit to update this template</strong></p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <h3><span class="custom-label">{{ template_to_update.name }}</span></h3>
                    </div>
                </div>

                <br />

                <div class="row">
                    <div class="col-xs-12">
                        <form action="" method="post">{% csrf_token %}
                            {{ form.as_p }}
                            <a href="{% url 'admin_updated_template' template_to_update.pk %}" class="btn custom-btn-default btn-lg" role="button">Cancel</a>
                            <input class="btn-primary pull-right btn-lg custom-btn" type="submit" value="Update"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock editorContent %}

templates/admin_level_template_edit.html
{% extends 'tinymce_editor_base.html' %}

{% comment %}
    Presents the text editor to an administrator so they can edit a template selected from the
    list of policy templates
{% endcomment %}

{% block editorContent %}

        <div class="row">
            <div class="col-xs-12" style="padding-right: 20px; padding-left: 40px">

                <div class="row">
                    <div class="col-xs-12 page-header">
                        <h1>AI Policy Wizard</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert custom-alert-info">
                            <p><strong>Edit to update this template</strong></p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <h3><span class="custom-label">{{ template_to_update.name }}</span></h3>
                    </div>
                </div>

                <br />

                <div class="row">
                    <div class="col-xs-12">
                        <form action="" method="post">{% csrf_token %}
                            {{ form.as_p }}
                            <a href="{% url 'policy_templates_list' %}" class="btn custom-btn-default btn-lg" role="button">Cancel</a>
                            <input class="btn-primary pull-right btn-lg custom-btn" type="submit" value="Update" />
                        </form>
                    </div>
                </div>

            </div>
        </div>

{% endblock editorContent %}

templates/admin_level_template_list.html
{% extends 'policy_template_list_base.html' %}


{% comment %}
    Presents policy templates to an administrator
{% endcomment %}


{% block instructions %}
    <h4>Instructions for Administrators</h4>
    <div class="highlighted">
        <ul>
            <li>As an administrator, you can edit to update these templates.</li>
        </ul>
    </div>
{% endblock instructions %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>AI Policy Wizard</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
      .smaller-h2 {
          font-size: 18px;
      }
      
      li {
          padding-bottom: 1em;
      }

      .page-header {
        padding-bottom: 9px;
        margin: 40px 0 20px;
        border-bottom: 1px solid #eee;
      }

      .custom-label {
          display: inline;
          padding: .2em .6em .3em;
          font-size: 75%;
          font-weight: 700;
          line-height: 1;
          color: #fff;
          text-align: center;
          white-space: nowrap;
          vertical-align: baseline;
          border-radius: .25em;
          background-color: #337ab7;
      }

      .custom-alert-info {
          color: #31708f;
          background-color: #d9edf7;
          border-color: #bce8f1;
      }

      .custom-btn-default {
          color: #333;
          background-color: #fff;
          border-color: #ccc;
      }

      .custom-card-header {
          background-color: white;
          border-bottom: none;
          padding: 1em;
      }

      .custom-btn {
          color: #fff;
          background-color: #337ab7;
          border-color: #2e6da4;
      }
      /* for Policy Text Bold */
      label[for="id_body"] {
          font-weight: 700;
      }
    </style>
    {% block extra_head %}
    {% endblock extra_head %}

  </head>
  <body>

    <div class="container">
      <main>
          {% block content %}
          {% endblock content %}
      </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" ></script>
    {% block extra_script %}
    {% endblock extra_script %}
  </body>
</html>

templates/instructor_level_policy_edit.html
{% extends 'tinymce_editor_base.html' %}

{% comment %}
    Presents text editor to an instructor
{% endcomment %}

{% block editorContent %}

        <div class="row">
            <div class="col-xs-12" style="padding-right: 20px; padding-left: 30px">
                <div class="row">
                    <div class="col-xs-12 page-header">
                        <h1>AI Policy Wizard</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert custom-alert-info" role="alert">
                            <p><strong>Customize your policy on collaboration for this class</strong></p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <a href="{% url 'policy_templates_list' %}" class="btn custom-btn-default btn-lg" role="button" >Cancel</a>
                            <input class="btn-primary pull-right btn-lg custom-btn" type="submit" value="Publish" />
                        </form>
                    </div>
                </div>

            </div>
        </div>

{% endblock editorContent %}

templates/instructor_level_template_list.html
{% extends 'policy_template_list_base.html' %}


{% comment %}
    Presents policy templates to an instructor
{% endcomment %}


{% block instructions %}
    <h2 class="smaller-h2">Instructions for Faculty</h2>
    <br />
    <ul>
        <li>All instructors are encouraged to include a policy regarding the use and misuse of generative AI. Whether students in your course are forbidden from using ChatGPT or expected to explore its limits, a policy helps ensure that your expectations for appropriate interaction with generative AI tools are clear to students. Once you decide on a policy, make sure you articulate it clearly for your students, so that they know what is expected of them.</li>
        <li>Below are options that you may adopt for your own policy. After selecting one, feel free to modify it to suit the needs of your course.</li>
        <li>Please reference the <a href="https://oue.fas.harvard.edu/ai-guidance" target="_blank">AI guidelines from the Harvard College Office for Undergraduate Education</a> for more information.</li>
        <!-- <li>As stated in <a href="http://infoforfaculty.fas.harvard.edu/" target="_blank"  class="alert-link">Information for Faculty</a>: “It is essential that instructors set out carefully in writing
            and at the outset of a course or course assignment the extent of permissible student collaboration
            in the preparation of papers, computer programs, or examinations. Students must assume that collaboration
            in the completion of assignments is permitted unless explicitly prohibited by the instructor. Students
            should be reminded that they are expected to acknowledge any collaboration and its extent in all
            submitted work.”</li>
        <li>Reviewing the the <a href="http://honor.fas.harvard.edu/" target="_blank" class="alert-link">Honor Code website</a> may be of assistance as you determine your policy,
            particularly the sections on the <a href="http://honor.fas.harvard.edu/affirmation" target="_blank" class="alert-link">Affirmation</a> and <a href="http://honor.fas.harvard.edu/teaching-integrity" target="_blank" class="alert-link">Teaching With Integrity</a>.</li>
        <li><strong>To prepare an AI policy for this class, choose 1 of the templates provided below and edit as appropriate. Also provided is an option to
            write your own policy from scratch.</strong></li> -->
    </ul>
{% endblock instructions %}

{% block customizePolicyBlock %}
<!-- <div class="card mb-3">
    <div class="custom-card-header">
        <h3><span class="custom-label">Blank Template</span></h3>
        <div style="margin-top: 1.5em;">
            <p>
                <em>If you choose to write your own policy on collaboration, keep the following guidelines in mind.</em>
            </p>
            <ol>
                <li>
                    You should outline explicitly what students may or may not discuss with their classmates outside the classroom and how best to capture those discussions on formal work submitted for course credit.
                </li>
                <li>
                    You may want to include citation resources for students including the <a href="http://usingsources.fas.harvard.edu/" target="_blank">Harvard Guide to Using Sources</a>.
                </li>
                <li>
                    You may want to include information about conforming to the College’s policies on academic integrity found in the <a href="http://handbook.fas.harvard.edu/" target="_blank">Harvard College Handbook for Students</a>.
                </li>
            </ol>
        </div>     
        <div class="row">
            <div class="col-xs-12">
                <a href="{% url 'instructor_level_policy_edit' custom_policy_template.pk %}">
                    <div style="position: relative">
                        <span class="icon-input-btn">
                            <button value="Create A Custom Policy" class="btn btn-primary btn-md pull-right custom-btn" type="submit" name="commit" >
                                <i class="fa fa-file-o" style="font-size: 1.3em; color: white;"></i>
                                Write From Scratch
                            </button>
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div> -->
{% endblock customizePolicyBlock %}

templates/instructor_published_policy.html
{% extends 'base.html' %}

{% comment %}
    Displays the published policy to the instructor.
    Also displayed are 2 buttons: 1 to enable them prepare a new policy from the list of policy templates
    and another to edit the policy they just published.
{% endcomment %}

{% block content %}
    <div class="row">
        <div class="col-sm-12" style="padding-right: 20px; padding-left: 30px">

            <div class="row">
                <div class="col-xs-12">
                    <h1>Academic Integrity Policy</h1>
                </div>

            </div>

            <br />
            <div class="row">
                <div class="col-xs-12">
                    <div class="alert alert-success" role="alert">
                        <strong>Your academic integrity policy has been published successfully.</strong>
                        <br>You can click the ‘Edit’ button to refine it or
                          the ‘Delete and prepare new policy from templates’ button to delete this policy and start afresh.
                    </div>

                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    {{ active_policy.body|safe }}
                </div>
            </div>

            <div class="row">
                <div class="col-xs-8">
                    <div>
                        <a class="btn btn-default" role="button" data-toggle="modal" data-target="#myModal">
                            <i class="fa fa-times-circle fa-flip-horizontal"></i>
                                Delete and prepare new policy from templates
                        </a>

                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h2 class="modal-title" id="myModalLabel">Warning</h2>
                              </div>
                              <div class="modal-body">
                                  <strong>Are you sure you want to delete your current published policy and customize a new one from the available templates?</strong>
                                  <br />
                                  <br />
                                  If you simply want to edit the current policy,
                                  click ‘Cancel’ and then access the text editor via the ‘Edit’ button.
                              </div>
                              <div class="modal-footer">
                                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
                                  <a type="button" class="btn btn-primary pull-right" href="{% url 'instructor_inactivate_old_prepare_new' active_policy.pk %}">Yes, <strong>DELETE</strong> and start afresh</a>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-4">
                    <a class="btn btn-primary pull-right" href="{% url 'edit_active_policy' active_policy.pk %}" role="button">
                        <i class="fa fa-pencil-alt fa-flip-horizontal"></i>
                        Edit
                    </a>
                </div>

            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_script %}
    <script type="text/javascript">
        $('#myModal').on('shown.bs.modal', function () {
          $('#myInput').focus()
        })
    </script>
{% endblock extra_script %}

templates/lti_exception.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
      <div class="col-xs-12" style="padding-right: 20px; padding-left: 30px">
          <div class="row">
              <div class="col-xs-12 page-header">
                  <h1>AI Policy Wizard</h1>
              </div>
          </div>
      </div>
  </div>

  <br>
  <div class="row">
      <div class="col-xs-12 col-md-6">
          <div class="alert custom-alert-info" role="alert">
              <p><strong>Something is wrong.</strong></p>
              <p>Your session may have timed out. Try refreshing your browser.</p>
              <p>If that fails there may be an issue with the Consumer Key or Shared Secret
                used to install this app.</p>
              <p>Contact atg@fas.harvard.edu if issues persist.</p>
          </div>
      </div>
  </div>

{% endblock content %}

templates/policy_edit.html
{% block content %}
    <h2>{{ policyTemplate.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Publish</button>
    </form>
{% endblock %}

templates/policy_template_edit.html
{% block content %}
    <h1>Edit Policy Template</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
{% endblock content %}

templates/policy_template_list_base.html
{% extends 'base.html' %}

{% comment %}
    Given that the administrator's and instructor's displays of policy templates are similar,
    this template abstracts out code common in the corresponding django templates.
{% endcomment %}

{% block content %}
    <div class="row">

        <div class="col-xs-12" style="padding-right: 20px; padding-left: 30px">
            <div class="row">
                <div class="col-xs-12 page-header">
                    <h1>AI Policy Wizard</h1>
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-xs-12">
                    <div class="alert custom-alert-info" role="alert">
                        {% block instructions %}
                        {% endblock instructions %}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    <div class="card">

                        <div class="card-header" style="color: #fff; background-color: #337ab7; border-color: #337ab7;">
                            <h2 class="smaller-h2" style="margin-top: 20px;">Templates</h2>
                        </div>
                        <div class="card-body" style="border: 1px solid #337ab7;">

                            <div class="card mb-3">
                                <div class="custom-card-header">
                                    <h3 class="mt-4 mb-2"><span class="custom-label">{{ maximally_restrictive_policy_template.name|safe }}</span></h3>
                                    <p style="margin-top: 1.4em;">{{ maximally_restrictive_policy_template.body|safe }}</p>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <a href="{% url list_level maximally_restrictive_policy_template.pk %}">
                                                <div style="position: relative">
                                                    <span class="icon-input-btn">
                                                        <button value="Choose {{ maximally_restrictive_policy_template.name|safe }} Template" class="btn btn-primary btn-md pull-right custom-btn" type="submit" name="commit">
                                                            <i class="fa fa-file-word-o" style="font-size: 1.3em; color: white;"></i>
                                                            {{ button_text }} Template
                                                        </button>
                                                    </span>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="card mb-3">
                                <div class="custom-card-header">
                                    <h3 class="mt-4 mb-2"><span class="custom-label">{{ mixed_policy_template.name|safe }}</span></h3>
                                    <p style="margin-top: 1.4em;">{{ mixed_policy_template.body|safe }}</p>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <a href="{% url list_level mixed_policy_template.pk %}">
                                                <div style="position: relative">
                                                    <span class="icon-input-btn">
                                                        <button value="Choose {{ mixed_policy_template.body|safe }} Template" class="btn btn-primary btn-md pull-right custom-btn" type="submit" name="commit" >
                                                            <i class="fa fa-file-word-o" style="font-size: 1.3em; color: white;"></i>
                                                            {{ button_text }} Template
                                                        </button>
                                                    </span>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card mb-3">
                                <div class="custom-card-header">
                                    <h3 class="mt-4 mb-2"><span class="custom-label">{{ fully_encouraging_policy_template.name|safe }}</span></h3>
                                    <p style="margin-top: 1.4em;">{{ fully_encouraging_policy_template.body|safe }}</p>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <a href="{% url list_level fully_encouraging_policy_template.pk %}">
                                                <div style="position: relative">
                                                    <span class="icon-input-btn">
                                                        <button value="Choose {{ fully_encouraging_policy_template.name|safe }} Template" class="btn btn-primary btn-md pull-right custom-btn" type="submit" name="commit">
                                                            <span class="fa-layers fa-fw">
                                                                <i class="fa fa-file-word-o" style="font-size: 1.3em; color: white;"></i>
                                                            </span>
                                                            {{ button_text }} Template
                                                        </button>
                                                    </span>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {% block customizePolicyBlock %}
                            {% endblock customizePolicyBlock %}

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock content %}

templates/student_active_policy.html
{% extends 'base.html' %}

{% comment %}
    Displays a course policy to a student of the course
{% endcomment %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">

            <div class="row">
                <div class="col-xs-12 page-header">
                    <h1>AI Policy</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    <p>{{ active_policy.body|safe }}</p>
                </div>
              </div>

        </div>
    </div>
{% endblock content %}

templates/student_published_policy.html
{% extends 'base.html' %}

{% comment %}
    Displays a course policy to a student of the course
{% endcomment %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">

            <div class="row">
                <div class="col-xs-12 page-header">
                    <h1>Academic Integrity Policy</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    <p>{{ active_policy.body|safe }}</p>
                </div>
              </div>

        </div>
    </div>
{% endblock content %}

templates/tinymce_editor_base.html
{% extends 'base.html' %}

{% comment %}
    Abstracts the html heads of the templates containing the tinymce editor
{% endcomment %}

{% load static %}

{% block extra_head %}
    <style>
        textarea {
            max-width: 100%;
            margin: 0;
            border: 0px solid #fff;
            position: relative;
            padding: 1em;
            height: 20em;
            -moz-box-sizing: border-box;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
        }
    </style>

    <script type="text/javascript" src="{% static 'tinymce/tinymce.min.js'%}"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: 'textarea',
            content_css: "{% static 'css/custom_content.css' %}",
            branding: false,
            theme: 'modern',
            plugins: 'textcolor lists table media link image directionality',
            menubar: false,
            toolbar1: 'bold italic underline forecolor backcolor removeformat alignleft aligncenter alignright outdent indent superscript subscript bullist numlist',
            toolbar2: 'table media link unlink image ltr rtl fontsizeselect formatselect'
        });
    </script>
{% endblock extra_head %}

{% block content %}

    {% block editorContent %}
    {% endblock editorContent %}

{% endblock content %}